# Name: Andrew M. Calhoun (calhouna)
# Email: calhouna@onid.oregonstate.edu
# Date: 6/24/2015
# Description: Make file for lab A, CS162. 
#
#



CXX = g++
CXXFLAGS = -std=c++0x

#target: dependencies
#	rule to build
#

default: average.cpp summation.cpp labAa-1.cpp
	g++ -std=c++0x average.cpp summation.cpp labAa-1.cpp -o labAa

